questions_list = ["Grand Central Terminal, Park Avenue, New York is the world's ...?",
                  "G-15 is an economic grouping of?",
                  "Hundred year war was fought between which of the following?",
                  "Which of the following is not associated with the UNO?",
                  "Amnesty International is an organisation associated with which of the following fields?",
                  "The headquarters of the UNESCO is located in?",
                  "Besides UK, USA, Germany and Japan the G-7 countries includes ...?",
                  "Who invented the Ballpoint pen?",
                  "What Benjamin Franklin invented?",
                  "Where was the yo-yo invented?",
                  "Which was the 1st non Test playing country to beat India in an international match?",
                  "Where did India play its 1st one day international match?",
                  "The Indian football team made its first appearance at Olympics in ...?",
                  "Who was the first captain of Indian Test team?",
                  "How many gold medals have been won by India in the Olympics so far?",
                  "The trident-shaped symbol of Buddhism does not represent ...?",
                  "Todar Mal was associated with ...?",
                  "Tipu sultan was the ruler of?",
                  "Chlorophyll is a naturally occurring chelate compound in which central metal is?",
                  "Quartz crystals normally used in quartz clocks is chemically?",
                  "Non stick cooking utensils are coated with?",
                  "The great Victoria Desert is located in?",
                  "Which is the largest animal on land?",
                  "Which is the largest animal in the world",
                  "What is a baby frog called?",
                  "Which song has the most views on YouTube?",
                  "What is the Italian word for PIE?",
                  "Water boils at 212 Units at which scale?",
                  "Which sea creature has three hearts?",
                  "Who was the character famous in our childhood rhymes associated with a lamb?",
                  "How many bones does an adult human have?",
                  "How many wonders are there in the world?",
                  "Which of the following elements does not exist?",
                  "Who is Loki?",
                  "Who was the first Indian female astronaut ?",
                  "The beaver is the national embelem of which country?"
                  ]

# First option is the correct answer for the corresponding question
options_list = [["largest railway station", "highest railway station", "longest railway station", "None of the above"],
                ["Third World Nations", "First World Nations",
                 "Second World Nations", "Fourth World Nations"],
                ["France and England", "Greek and Persian forces",
                 "Civil war in England", "None of the above"],
                ["ASEAN", "ILO", "WHO", "UNESCO"],
                ["Protection of human rights", "Protection of Cruelty to animals",
                 "Environment protection", "Protection of historic monuments"],
                ["Paris", "New York", "Rome", "Geneva"],
                ["Canada, France and Italy", "Canada, France and Russia",
                 "Canada, Italy and Netherlands", "France, Netherlands and Russia"],
                ["Biro Brothers", "Waterman Brothers",
                 "Bicc Brothers", "Wright Brothers"],
                ["Bifocal spectacles", "Radio", "Barometer", "Hygrometer"],
                ["Philippines", "France", "United States", "England"],
                ["Sri Lanka", "Zimbabwe", "Canada", "Kenya"],
                ["Headingley", "Lords", "The Oval", "Eden Gardens"],
                ["1948", "1936", "1952", "1956"],
                ["C K Nayudu", "Vijay Hazare", "Lala Amarnath", "Vijay Merchant"],
                ["9", "8", "10", "6"],
                ["Nirvana", "Sangha", "Buddha", "Dhamma"],
                ["Finance", "Law", "Music", "Literature"],
                ["Mysore", "Hyderabad", "Madurai", "Vijayanagar"],
                ["Magnesium", "Copper", "Iron", "Calcium"],
                ["silicon dioxide", "germanium oxide",
                 "a mixture of germanium oxide and silicon dioxide", "sodium silicate"],
                ["Teflon", "Polystyrene", "PVC", "Black Paint"],
                ["Australia", "Canada", "United States", "South Africa"],
                ["African elephant","Blue Whale","Humming Bird","Whale shark"],
                ["Blue Whale","Humming Bird","African elephant","Whale shark"],
                ["Tadpole","Caterpillar","Pupa","Pollipole"],
                ["Despacito","Baby","Shake it off","Taki Taki"],
                ["Pizza","Mozarella","Pasty","Patty"],
                ["Fahrenheit","Celsius","Rankine","Kelvin"],
                ["Octopus","Walrus","Seal","Dolphin"],
                ["Mary","Jack","Johnny","Jill"],
                ["206","208","201","204"],
                ["7","8","6","10"],
                ["Xf","Re","Si","Pa"],
                ["God of Mischief","God of Gods","God of Dwarves","God of Thunder"],
                ["Kalpana Chawla","Priya Ghoshal","Sunita Williams","None of the above"],
                ["Canada","Argentina","Iceland","Zimbabwe"],
                ]
